#
# Module manifest for module 'Odd-Commands'
#
# Generated by: Nick Marsceau
#
# Generated on: 2/5/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Odd-Commands.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = '8419f50a-4f6e-48d4-9617-685cfb218f82'

# Author of this module
Author = 'Nick Marsceau'

# Description of the functionality provided by this module
Description = 'Odd Commands is a PowerShell tool for storing and running commands you may not use frequently and are too long or awkward to memorize.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Invoke-OddCommands')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('oc')

# List of all modules packaged with this module
ModuleList = @('Odd-Commands')

# List of all files packaged with this module
FileList = @('.gitignore', 'LICENSE', 'Odd-Commands.psd1', 'Odd-Commands.psm1', 'README.md')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # A URL to the license for this module.
        LicenseUri = 'https://github.com/nmarsceau/odd-commands/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/nmarsceau/odd-commands'
    }
}
}

